name: dart_graphql
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '2.16.2'


dependencies:
  args: '2.3.0'
  shelf: '1.3.0'
  shelf_router: '1.1.2' 
  shelf_plus: '1.2.2'
  mongo_dart: '0.7.4'
  objectid: '2.1.0' 
  leto_schema: '0.0.1'
  leto: '0.0.1'
  leto_shelf: '0.0.1'

dev_dependencies:
  http: '0.13.4'
  lints: '1.0.1'
  test_process: '2.0.2'
  test: '1.20.2'
  build_runner: '2.1.8'

# leto is not available on pub just yet
dependency_overrides:
  leto_generator:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto_generator
  leto:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto
  leto_schema:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto_schema
  leto_shelf:
    git:
      url: https://github.com/juancastillo0/leto
      path: leto_shelf