name: dart_web
description: A new Flutter project.

environment:
  sdk: '2.16.2'

dependencies:  
  flutter:
    sdk: flutter

dev_dependencies:
  redux: "5.0.0"
  flutter_redux: "0.9.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true