services:    
  dart-server:
    build: ./dart-server/
    ports:
      - 80:8080
    restart: on-failure
    depends_on:
      - mongo      
    links:
      - mongo 
  dart-graphql:
    build: ./dart-graphql/
    ports:
      - 3000:3000
    environment:
      - HOST=192.168.50.101
      - PORT=3000
    restart: on-failure
    depends_on:
      - mongo      
    links:
      - mongo       
  mongo:
    build: ./mongo/
    ports:
      - 27017:27017
    volumes:
      - ~/temp:/data/db