services:
  dart_server:
    container_name: dart_server    
    build: ./dart_server/
    ports:
      - 80:8080
    environment:        
        - GRAPH_URL=http://192.168.50.101:3000/graphql
    restart: on-failure
    depends_on:
      - dart_graphql      
    links:
      - dart_graphql
  dart_graphql:
    container_name: dart_graphql
    build: ./dart_graphql/
    ports:
      - 3000:3000
    environment:
      - HOST=192.168.50.101
      - PORT=3000
      - MONGO_URL=mongodb://192.168.50.101:27017/my_database
    restart: on-failure
    depends_on:
      - mongo      
    links:
      - mongo       
  mongo:
    container_name: mongo
    build: ./mongo/
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - ~/temp:/data/db